# Generated by Django 4.2.4 on 2023-08-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('us', 'user'), ('rp', 'representative')], default='us', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=uuid.UUID('bae43e7a-a827-4737-839a-7a6be4b6910f'), max_length=50)),
                ('request_title', models.CharField(max_length=100)),
                ('request_status', models.CharField(choices=[('In Progress', 'in_progress'), ('Resolved', 'resolved')], default='In Progress', max_length=50)),
                ('service_request_type', models.CharField(choices=[('Gas Cylinder Delivery', 'Gas Cylinder Delivery'), ('Gas Leakage Complaint', 'Gas Leakage Complaint'), ('Change of Contact Details', 'Change of Contact Details'), ('Payment Related Issues', 'Payment Related Issues')], default='Gas Cylinder Delivery', max_length=50)),
                ('details', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
